name: learning docker
on:
  push:
    branch:
      - testing-pipeline
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout our repository
        uses: actions/checkout@v3

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: "18"

      - name: Build the Docker Image :)
        run: docker build -t akamprogramist/frontend-web-store-lab4:akamprogramist/frontend-web-store-lab4

      - name: Log in to the Docker hub :>
        run: docker login -u ${{secrets.DOCKERHUB_USERNAME}} -p ${{secrets.DOCKERHUB_TOKEN}}

      - name: Push the docker to dockerhub ;)
        run: docker push akamprogramist/frontend-web-store-lab4:akamprogramist/frontend-web-store-lab4
